---
proxmox_apt_keys:
  - url: "https://enterprise.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release | lower }}.gpg"
    id: "28139A2F830BD68478A1A01FDD4BA3917E23BF59"

proxmox_apt_repositories:
  pve-enterprise:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release | lower }} pvetest"

proxmox_package_state: present
proxmox_packages:
  util:
    - skopeo

proxmox_sysctl_config:
  kernel.dmesg_restrict: 0
  kernel.pid_max: 100000
  user.max_user_namespaces: 150000
  vm.compact_memory: 1
  vm.overcommit_memory: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1
  net.ipv4.ip_nonlocal_bind: 1

proxmox_modules:
  - fuse
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - br_netfilter
  - iptable_nat
