---
- name: apt repo keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ base_apt_keys }}"
- name: apt repos
  apt_repository:
    repo: "{{ item.value.repo }}"
    filename: "{{ item.key }}.list"
    state: "{{ item.value.state | default('present')}}"
  loop: "{{ lookup('dict', base_apt_repositories, wantlist=True) | default({}) }}"
- name: install packages
  package:
    name: "{{ item.value }}"
    state: "{{ base_package_state }}"
  loop: "{{ (base_packages | default({})) | dict2items }}"
